name: CI - Karate + SonarQube + Plugin personalizado

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and install dependencies
      working-directory: karate-demo
      run: mvn clean install -DskipTests

    - name: SonarQube Scan
      working-directory: karate-demo
      env:
        SONAR_TOKEN: sqp_74b96721dfae5be29c2b693f70f254896f9e819b
      run: mvn sonar:sonar -Dsonar.projectKey=chapterQA-Karate -Dsonar.host.url=https://chapter-karate-sonarqube.host -Dsonar.login=sqp_74b96721dfae5be29c2b693f70f254896f9e819b

    - name: Run Karate tests
      working-directory: karate-demo
      run: mvn test

    - name: Upload Karate test reports
      uses: actions/upload-artifact@v4
      with:
        name: karate-test-reports
        path: target/surefire-reports/
